# Site
name: "Product Growth Stories"
description: "Growth, Product Management, and Startups - Martín Goycoolea"
meta_description: "How to analyze, manage, and grow digital products."
logo: '/assets/images/logo.svg'
favicon: '/assets/images/logo.svg'
baseurl: ''
#google_analytics: ""
#disqus: ""
#mailchimp-list: ""

# Authors
authors:
  martin:
    name: Martin
    display_name: Martin
    gravatar: 268ae3f005c2c3398ce4233182a738e5
    email: mgoysco@gmail.com
    web: "https://mgoy.co"
    twitter: "https://www.twitter.com/mgoycoolea"
    description: "Adventurer"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
